[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/weaveworks/flux"
  version = "1.14.2"

[[override]]
  name = "github.com/go-kit/kit"
  version = "0.9.0"

[[override]]
  name = "github.com/Jeffail/gabs"
  version = "v1.4.0"

[[override]]
  branch = "release-1.15"
  name = "k8s.io/apimachinery"

[[override]]
  branch = "release-1.15"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.15"
  name = "k8s.io/apiextensions-apiserver"

[[override]]
  revision = "kubernetes-1.15.0"
  name = "k8s.io/client-go"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"
